### ISSUE TITLE
a4091 -t crashes/hangs at BUS Test (-t4)

### ISSUE THREAD

**Issue by tkurbad** [A4091/a4091-software#14]
Hi,

I think, introducing commit 7251675940e25d74161107a911cdb64ac54ba838 without the appropriate GAL changes causes the test utility to hang during the bus test.

Perhaps this should be postponed until after the necessary logic adaptions...

Best
Torsten

**Comment by tkurbad** [comment]
Hmm, reversed the aforementioned commit. Bus test still hangs.

**Comment by tkurbad** [comment]
Upon further testing, this seems to be accelerator-dependent: On overclocked BFG9060 and CSPPC (both with 68060), I get a SIOP timeout: 31 ticks

On BFG9060 with 68040 @37.5 MHz, it freezes the machine.

**Comment by reinauer** [comment]
Can you confirm that this does not happen with the 42.25 release? Can you try the 42.26 a4091 utility with the 42.25 rom?

Both the rom and the utility changed in the 42.26 release.

**Comment by tkurbad** [comment]
I tried all combinations now. It seems independent from utility and ROM version - I guess it's a GAL problem.

**Comment by tkurbad** [comment]
Here's the output of a failing 'a4091 -t4 -d'
[t4.txt](https://github.com/A4091/a4091-software/files/13256330/t4.txt)

**Comment by cdhooper** [comment]
The -t4 executed the following read-from-address tests:

ROM 40000000           Pass  (A4091 ROM base fetch)
 A3 -        00020028  Pass
 A4 00020020 00020030  Pass
 A5 00020000 00020020  Pass
 A6 00020000 00020040  Pass
 A7 00020000 00020080  Pass
 A8 00020000 00020100  Pass
 A9 00020000 00020200  Pass
A10 00020000 00020400  Pass
A11 00020000 00020800  Pass
A12 00020000 00021000  Pass
A13 00020000 00022000  Pass
A14 00020000 00024000  Pass
A15 00020000 00028000  Pass
A16 00020000 00030000  Pass
A17 00040000 00060000  Pass
A18 00020000 00060000  Pass
A19 00020000 000a0000  Pass
A20 00020000 00120000  Pass
A21 08400000 08600000  Pass
A22 08800000 08c00000  Pass
A23 08400000 08c00000  Pass
A24 08400000 09400000  Pass
A25 08400000 0a400000  Pass
A26 08400000 0c400000  Pass
A27 07000020 0f000020  Fail  SIOP timeout on fetch from 07000020
                             Fetch from 0f000020 was good
A28 -        50000020  Pass
A30 -        50000020  Pass

The fetch that failed (address 0x07000020) is at the base of motherboard fastmem. It was the only fetch in this case which targeted fastmem, and so probably the only fetch which would have been met with STERM rather than DSACK. I don't know if that is an issue at this point or if it's that the 53C710 never received the write command ([4080002c] W 07000020) to start DMA, or whether 0x07000020 is somehow off limits for memory allocation. I could probably add some more code to detect memory corruption at 0x07000020. Will look into this.

**Comment by tkurbad** [comment]
Just to be sure I'll do a memcheck of the MB fastmem area tonight (after the current card finished its 4000 devtest loops. ;-)

**Comment by tkurbad** [comment]
Problem solved (kind of)! One of the FastRAM SIMMs wasn't properly inserted. According to Amiga Testkit, only 4 MB of 16 were detected, starting 0x07c00000. Does a4091 -t honor the list of autodetected memory segments?

**Comment by cdhooper** [comment]
That's quite interesting. a4091 -t does honor the list of autodetected memory segments. In fact, that list gets walked by alloc_power2_addr() when searching for addresses in the free list that match the requirements for addresses which both have and do not have the required particular address bit set.

**Comment by cdhooper** [comment]
Sorry, I didn't mean to close this issue. I am wondering if when your FastRAM SIMM was not fully seated, that it was still getting detected by the OS startup code even though the memory was not fully working.

**Comment by cdhooper** [comment]
The lingering question here is what we can do in the test utility to help diagnose this kind of issue. One thing that I think might be useful is for when we do have an SIOP timeout while running this test, the utility should probably not only report the address bit which failed, but also the address which was being used for the test.
